language: R
cache: packages
sudo: false

r: 
- release 
- devel

os:
- linux
- osx

bioc_packages: 
- multtest

r_packages:
- reshape2
- GSA
- gtools
- cluster
- splines
- gplots
- stats
- graphics
- grDevices
- utils
- lme4
- gtable
- scales
- tibble
- lazyeval
- foreach
- doParallel
- tcgsaseq
- knitr
- rmarkdown
- viridisLite

r_github_packages:
- hadley/scales
- hadley/ggplot2
- hadley/stringr

r_build_args: "--html"

r_check_args: "--as-cran --timings"
